[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.flash_mode = qio
board_upload.flash_size = 16MB

build_flags =
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE

lib_deps =
    lvgl/lvgl
    moononournation/GFX Library for Arduino
    bblanchon/ArduinoJson
    knolleary/PubSubClient