name: PlatformIO CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Create dummy config.h
        run: cp src/config.example.h src/config.h

      - name: Build firmware
        run: pio run